### ISSUE TITLE
Coverage representation in HTML

### ISSUE THREAD

**Issue by pebau** [opengeospatial/ogc_api_coverages#14]
Currently discussion of HTML seems to mostly concentrate on encoding coverage metadata in HTML, ie: not the range set. If we talk about encoding a _complete_ coverage we need to establish an HTML encoding including the range set. (Sometimes an image can be rendered: if the coverage is 2D and contains 1 or 3 integer bands.)

**Comment by Schpidi** [comment]
Teleconference 20190426: It's agreed that HTML is not a suitable format for coverage's range set.

**Comment by pebau** [comment]
Here is a sample HTML frontend for coverages, is that what you have in mind with an HTML delivery?
http://ows.rasdaman.org/rasdaman/wcs-client/index.html

**Comment by pvgenuchten** [comment]
when noticing this discussion, i wondered if the use case "browsing the api through a browser" has been considered. To me it makes sense to have a html representation for any api-level, with option to drill down to lower levels. I agree that representing actual pixel values as a html-table may not be very sensible, but one level up would make sense to have a html page with links to the actual grids as image

**Comment by nmtoken** [comment]
> one level up would make sense to have a html page with links to the actual grids as image

That assumes that the coverage is 2D and a grid and/or can be represented as a 2D image, and that isn't true for all coverages. 

I think there would be an issue too for very large coverages, you'd want some sub-setting, or scaling operations rather than the whole coverage. 

I was thinking that by links you meant like `<img src...>` or `<a href...>` but I can see that an HTML form that allowed users to select options to create a query to get a coverage as an image, where it was possible, would also be a link.

**Comment by pebau** [comment]
this reminds me of WCPS which could be typed into a form, or as part of a prefabricated link. Here is a demo (select a query from the bottom of the page, then press "execute"):
http://earthlook.eecs.jacobs-university.de/new_earthlook/index.html?page=demo-apps&?group=geo-service-standard&app=wcps

**Comment by cmheazel** [comment]
@pvgenuchten One possibility would be an HTML page (or pages) for the collection a thumbnail for each coverage.  Only works for 2-D images, but it is a common approach we should consider.

**Comment by Schpidi** [comment]
The design overview of [STAC](https://github.com/radiantearth/stac-spec) says: "An important core principle of the STAC design is to embrace best practices of making data available on the web (like [HATEOAS](https://en.wikipedia.org/wiki/HATEOAS) ...". I find this quite interesting.

**Comment by pebau** [comment]
who decides when a practice is best? ;-)
If we do an HTML encoding we might just translate the XML schema into HTML, a low-hanging fruit (except that HTML has no schema / has a frozen schema). So a coverage would become an HTML snippet which can be embedded anywhere (and styled).

**Comment by cmheazel** [comment]
Current version (12/30/19) treats the range set (pixels) different from the other content. 
Since the Range Set is usually binary data, we can expect most APIs to deliver range set data in a binary format. Everything else can be delivered in HTML. For combined deliveries, a multi-part mime-type can be used to combine the binary data with HTML.  All of which is supported by HTTP content negotiation.

**Comment by pebau** [comment]
Can you please point us to where exactly that different behavior is specified?

**Comment by Schpidi** [comment]
https://github.com/opengeospatial/ogc_api_coverages/issues/13#issuecomment-655530732
