### ISSUE TITLE
SWG Charter

### ISSUE THREAD

**Issue by cmheazel** [opengeospatial/ogc_api_coverages#70]
What is the scope of this SWG and does the proposed charter accommodate it?

**Comment by pebau** [comment]
my suggestion:
- maintain the coverage data standards suite
- maintain the coverage service standards suite, including WCS and OAPI-Coverages, in both core and extension

**Comment by chris-little** [comment]
@pebau @cmheazel @Schpidi 
Do not forget that last year, the WCS SWG agreed to support the effort to standardise CoverageJSON, from Jon Blower and Marc Reickhart at Reading University. It now has quite wide implementation in the evironmental communities, but no formal definition. This is an opportunity to make it more compatible with wider standards, especially since the evolution of JSON-LD .

**Comment by cmheazel** [comment]
The Charter was updated in an on-line editing session on June 25, 2020.  We believe that the above issues have been covered.  The updated charter can be found in the "Charter" branch of the GitHub repository.

**Comment by ayoumans** [comment]
I just read it over and like it--nice!
