### ISSUE TITLE
Make use of HTTP headers

### ISSUE THREAD

**Issue by Schpidi** [opengeospatial/ogc_api_coverages#9]
For example, format should be requested using standard http headers as defined in [RFC2616](https://tools.ietf.org/html/rfc2616) like Accept and Accept-Encoding and reported with Content-Type.

**Comment by chris-little** [comment]
I agree HTTP content negotiation is the preferred solution, but sometimes some parts  of the Internet discards some HTTP headers, which is why 'fmt=xxx' was sometimes used. The two approaches are not exclusive or incompatible, and 'fmt=xxx' in the query could be used as a back-up.

**Comment by Schpidi** [comment]
Reading the OpenAPI specification the actual RFC to follow is [RFC 7231](https://tools.ietf.org/html/rfc7231).

**Comment by nmtoken** [comment]
Wondering out loud how this will work for WMS requests where more that two formats are negotiated in a single request...

> http://ogc.bgs.ac.uk/cgi-bin/BGS_BGS-HPA_Radon_Potential/wms?language=eng&VERSION=1.3.0&REQUEST=GetMap&CRS=EPSG:4326&BBOX=50.179445759563,-4.41340973640857,50.9615344710795,-3.2834397199341&WIDTH=877&HEIGHT=607&LAYERS=GBR_BGS-HPA_625K_RADON_POTENTIAL&STYLES=&EXCEPTIONS=XML&FORMAT=image/png&BGCOLOR=0xFEFFFF&TRANSPARENT=TRUE&

**EXCEPTIONS=XML&FORMAT=image/png&**

or

> http://ogc.bgs.ac.uk/cgi-bin/BGS_BGS-HPA_Radon_Potential/wms?language=eng&SERVICE=WMS&VERSION=1.3.0&REQUEST=GetFeatureInfo&BBOX=52.804653,-1.577809,52.959911,-1.349062&CRS=EPSG:4326&WIDTH=662&HEIGHT=450&LAYERS=GBR_BGS-HPA_625K_RADON_POTENTIAL&STYLES=&TRANSPARENT=true&QUERY_LAYERS=GBR_BGS-HPA_625K_RADON_POTENTIAL&INFO_FORMAT=text/html&FORMAT=image/png&I=194&J=162&

**INFO_FORMAT=text/html&FORMAT=image/png&**

Not a concern for WCS perhaps but must surely affect decisions about core?

**Comment by Schpidi** [comment]
20190412 WCS.SWG Telecon: How to extend examples with HTTP headers?

**Comment by pvgenuchten** [comment]
a typical use case for overriding header-content-negotiation via a querystring parameter is this: user arrives at api with a web browser, user receives the html representation due to the accept header. User clicks a button to view either xml or json representation. The button activates the same url, but with a param ?f=json

**Comment by cmheazel** [comment]
I think it is reasonable to define a common way to set (or override) some header values when the headers are not directly accessible (ex. a URL).  Content negotiation is a prime case.  API-Features (WFS 3.0) addresses this using the f= parameter.   So consider this scenario:
I have a document with two URLs.  Both point to the same resource, but one wants the GeoJSON representation and the other wants the GML representation.  The path should be the same in both URLs since they identify the same resource.  What is the Web best practice to distinguish one from the other?

**Comment by Schpidi** [comment]
The README.md has been extended to include both approaches whereas a present query parameter is given preference over HTTP headers.
